FROM cypress/base:10
WORKDIR /app

# dependencies will be installed only if the package files change
COPY ./rafflery-ui/package.json .
COPY ./rafflery-ui/package-lock.json .


RUN npm install
#RUN npm cypress verify
RUN npm run cypress:run
