FROM cypress/base:10
#FROM cypress/browsers:chrome69

WORKDIR /app

#COPY ./rafflery-ui .
#COPY ./rafflery-ui/node_modules ./node_modules

RUN pwd
RUN ls -la

# npm install doesnt work because he cant find /root/.cache
# can we fix this or do we just run npm ci always?
#RUN npm ci
RUN npm install

# do we need that stupid thing?
#RUN npm install xvfb

RUN npm run cypress:verify
