# we need a docker compose file for running cypress together with the backend
# because only starting the backend as a docker container cant expose the port
# for security reasons. cypress needs to run in the same docker context
# docker-compose.yml

version: '3'
services:
 backend:
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    - JWT_CLIENTID
    - JWT_ISSUER
    - PORT
 cypress:
   build:
     context: .
     dockerfile: Dockerfile.cypress
   depends_on:
      - "backend"
   #network_mode: 'host'
   environment:
      - CYPRESS_baseUrl=http://backend:8080
   command:
      - /bin/bash
      - -c
      - |
        npm run cypress:run --reporter junit --reporter-options
        pwd
        ls
