# we need a docker compose file for running cypress together with the backend
# because only starting the backend as a docker container cant expose the port
# for security reasons. cypress needs to run in the same docker context
# docker-compose.yml

version: '3'
services:
 backend:
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "8080:8080"
 cypress:
   build:
     context: .
     dockerfile: Dockerfile.cypress
   depends_on:
      - "backend"
   environment:
      - CYPRESS_baseUrl=http://backend
   command: npm run cypress:run
