version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:12.1.0 # our steps run in this container
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "rafflery-ui/package.json" }}
      - run:
          name: install-npm-wee
          command: cd rafflery-ui && npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "rafflery-ui/package.json" }}
          paths:
            - ./rafflery-ui/node_modules
      - run: # run tests
          name: test
          command: cd rafflery-ui && npm test
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results.xml
          prefix: tests
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml
  deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
