fast-checkout: &fast-checkout
  attach_workspace:
    at: ~/
    
version: 2
jobs:
  checkout_rafflery:
    docker:
      - image: python
    steps:
      - checkout
      - run: rm -rf .git
      - persist_to_workspace:
          root: /root
          paths:
            - project
  build_test_frontend:
    docker:
      - image: circleci/node:12.1.0
    steps:
      - *fast-checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "rafflery-ui/package.json" }}
      - run:
          name: install-npm
          command: cd rafflery-ui && npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "rafflery-ui/package.json" }}
          paths:
            - ./rafflery-ui/node_modules
            - ~/.cache
            - ~/.npm
      - run:
          name: Test Frontend
          command: cd rafflery-ui && npm run test:ci
      - store_artifacts:
          path: rafflery-ui/out/junit/test-results.xml
      - store_artifacts:
          path: rafflery-ui/out/coverage/lcov.info
      - store_test_results:
          path: rafflery-ui/out
      - run:
          name: build
          command: cd rafflery-ui && npm run build
      - run:
          name: copy build to different dir
          command: cp -R rafflery-ui/build ./build-frontend
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - build-frontend
  build_test_backend:
    docker:
      - image: gradle:jdk8
    steps:
      - *fast-checkout
      - run:
          name: build with gradle
          command: ./gradlew clean build
      - run:
          name: copy build to different dir
          command: cp -R rafflery-server/build ./build-backend
      - persist_to_workspace:
          root: /root/project
          paths:
            - build-backend
  build_docker:
    machine: 
      services:
        - docker
    steps:
      - *fast-checkout
      - run: pwd && ls
      - run: cd ./rafflery-ui && ls
      - run: cp -R /home/circleci/build-frontend .
      - run: cp -R /home/circleci/build-backend .
      - run:
          name: Build docker image
          command: |
            docker build --build-arg frontendBuild=./build-frontend --build-arg backendBuild=./build-backend/libs/rafflery.jar -t registry.heroku.com/rafflery/web .
      - run:
          name: Save docker image tag
          command: |
            docker save -o ./rafflery.tar registry.heroku.com/rafflery/web
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project/rafflery.tar
  build_test_end2end:
    docker:
      - image: cypress/browsers:chrome67
    steps:
      - *fast-checkout
      - run:
          name: Print working dir
          command: |
            pwd
            ls
      - run:
      # it would be better to have a docker image with cypress and docker
      #    name: Install Docker client (replace later with docker container with cypress and docker)
      #    command: |
      #      set -x
      #      VER="17.03.0-ce"
      #      curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
      #      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #      mv /tmp/docker/* /usr/bin
      # cant run docker without this
      - setup_remote_docker 
      - run: 
          name: Show docker version
          command: |
            docker version
      - run:
          name: Load docker image from .tar file
          command: |
            docker load -i rafflery.tar
      - run: 
          name: Run rafflery backend
          command: |
            docker run -it -p 8080:8080 --rm registry.heroku.com/rafflery/web:latest
      # why does it install cypress again here? shouldnt this be cached because of the
      # frontend build where we saved the cache?
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "rafflery-ui/package.json" }}
      - run:
          name: install-npm
          command: |
            cd rafflery-ui && npm install
      - run:
          name: Run cypress
          command: |
            cd rafflery-ui && npm run cypress:run
  deploy:
    machine: 
      services:
        - docker
    steps:
      - *fast-checkout
      - run:
          name: Install heroku cli
          command: |
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Login to heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Build docker image
          command: |
            docker build --build-arg frontendBuild=./build --build-arg backendBuild=./build/libs/rafflery.jar -t registry.heroku.com/rafflery/web .
      - run:
          name: Deploy heroku docker container
          command: |
            docker push registry.heroku.com/rafflery/web:latest
      - run:
          name: Release heroku docker container
          command: |
            heroku container:release web -a rafflery
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - checkout_rafflery
      - build_test_frontend:
          requires:
            - checkout_rafflery
      - build_test_backend:
          requires:
            - checkout_rafflery
      - build_docker:
          requires:
            - build_test_frontend
            - build_test_backend
      - build_test_end2end:
          requires:
            - build_docker
      - deploy:
          requires:
            - build_test_end2end
